name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - run: swift test --enable-code-coverage
      - name: swifty-code-coverage
        uses: michaelhenry/swifty-code-coverage@v1.0.1
        with:
          build-path: .build
          target: SwiftVectors.xctest
          is-spm: true
          output: "coverage/lcov.info"
          output-artifact-name: "codecov-artifact"
      - name: Upload to Codecov
        run: |
          bash <(curl https://codecov.io/bash) -f "coverage/*.info"
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
