name: CI
on:
  push:
  pull_request:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9'
      - run: swift build -v
      - run: swift test --enable-code-coverage
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: swift build -v
      - run: swift test --enable-code-coverage
